<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }}{{ $documentType ? ' - '.$documentType : '' }}{{ ($hospital ?? 'exclude') === 'only' ? '-H' : '' }}</title>
    <style>
        @page { margin: 12mm 8mm 14mm 8mm; }
        * { font-family: DejaVu Sans, sans-serif; }
        body { font-size: 8.5px; color: #111; margin: 0; }
        .page-break { page-break-after: always; }
        .head { text-align: center; margin-bottom: 6px; }
        .org { font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: .5px; }
        .office { font-size: 10px; font-weight: bold; margin-top: 1px; }
        .title { font-size: 15px; font-weight: bold; margin-top: 3px; }
        .sub { font-size: 9px; color: #444; margin-top: 3px; }
        .gen { font-size: 8px; color: #666; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        th, td { border: 0.5px solid #999; padding: 3px 4px; vertical-align: top; word-wrap: break-word; overflow-wrap: break-word; }
        thead th { background: #eee; font-size: 8px; text-transform: uppercase; letter-spacing: .3px; }
        .summary { margin-top: 8px; padding: 6px 8px; background: #f5f5f5; border: 0.5px solid #ccc; border-radius: 2px; font-size: 8.5px; }
        .summary b { font-size: 9px; }
        .note { margin-top: 4px; font-size: 7.5px; color: #888; font-style: italic; }
        .status-open { color: #b45309; }
        .status-closed { color: #15803d; }
    </style>
</head>
<body>
    @php
        $a = ($align ?? []) + [
            'date_encoded'=>'center','tracking_code'=>'center','title'=>'left','document_type'=>'center','origin'=>'left',
            'current'=>'left','status'=>'center','age'=>'center','last_action'=>'center','idle'=>'center',
        ];
        $cl = ($colLabels ?? []) + [
            'date_encoded'=>'Date Encoded','tracking_code'=>'Code','title'=>'Title','document_type'=>'Type','origin'=>'Origin',
            'current'=>'Current Location','status'=>'Status','age'=>'Age (since encoded)',
            'last_action'=>'Last Action','idle'=>'Idle Time',
        ];
        $w = [
            'num'=>'3%','date_encoded'=>'9%','tracking_code'=>'8%','title'=>'15%','document_type'=>'7%','origin'=>'12%',
            'current'=>'12%','status'=>'7%','age'=>'9%','last_action'=>'9%','idle'=>'9%',
        ];
        $cols = ['date_encoded','tracking_code','title','document_type','origin','current','status','age','last_action','idle'];
        $fmt = fn ($d) => $d->format('M j, Y'.($d->format('H:i') !== '00:00' ? ' g:i A' : ''));
        $period = ($from && $to) ? $fmt($from).' – '.$fmt($to) : ($from ? 'From '.$fmt($from) : ($to ? 'Up to '.$fmt($to) : 'All dates'));
        $hosp = ($hospital ?? 'exclude') === 'only' ? ' · Hospital only' : (($hospital ?? '') === 'include' ? ' · incl. Hospital' : '');
        // ->values() first so chunked sub-collections keep continuous 0-based keys for row numbering.
        $pages = $rows->values()->chunk($perPage ?? 14);

        $originOf = function ($doc) {
            $dept = $doc->creator?->department?->code;
            $div = $doc->creator?->division?->code;
            return trim(($dept ?: '—').($div ? ' / '.$div : ''));
        };
        $currentOf = function ($doc) {
            $dept = $doc->department?->code;
            $div = $doc->division?->code;
            return trim(($dept ?: '—').($div ? ' / '.$div : ''));
        };
    @endphp

    @forelse($pages as $chunk)
        <div class="{{ $loop->last ? '' : 'page-break' }}">
            <div class="head">
                @if($org)<div class="org">{{ $org }}</div>@endif
                @if(!empty($officeName))<div class="office">{{ $officeName }}</div>@endif
                <div class="title">{{ $reportTitle }}</div>
                <div class="sub">{{ $documentType ?: 'All document types' }} &middot; {{ $period }}{{ $hosp }} &middot; Sorted by: {{ $sortLabel ?? 'Date Encoded' }}</div>
                <div class="gen">Generated by {{ $generatedBy }} &middot; {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </div>

            <table>
                <colgroup>
                    <col style="width:{{ $w['num'] }}">
                    @foreach($cols as $c)<col style="width:{{ $w[$c] }}">@endforeach
                </colgroup>
                <thead>
                    <tr>
                        <th style="width:{{ $w['num'] }};text-align:center">#</th>
                        @foreach($cols as $c)
                            <th style="width:{{ $w[$c] }};text-align:{{ $a[$c] }}">{{ $cl[$c] }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($chunk as $rowNum => $doc)
                        @php
                            $isOpen = ! $doc->isClosed();
                            $ageSecs = $doc->created_at->diffInSeconds($doc->isClosed() ? $doc->updated_at : now());
                        @endphp
                        <tr>
                            <td style="text-align:center">{{ $rowNum + 1 }}</td>
                            <td style="text-align:{{ $a['date_encoded'] }}">{{ $doc->created_at->format('M j, Y g:i A') }}</td>
                            <td style="text-align:{{ $a['tracking_code'] }}">{{ $doc->tracking_code }}</td>
                            <td style="text-align:{{ $a['title'] }}">{{ $doc->title }}</td>
                            <td style="text-align:{{ $a['document_type'] }}">{{ $doc->document_type }}</td>
                            <td style="text-align:{{ $a['origin'] }}">{{ $originOf($doc) }}</td>
                            <td style="text-align:{{ $a['current'] }}">{{ $currentOf($doc) }}</td>
                            <td style="text-align:{{ $a['status'] }}" class="{{ $isOpen ? 'status-open' : 'status-closed' }}">{{ \App\Models\Document::statusLabel($doc->status) }}</td>
                            <td style="text-align:{{ $a['age'] }}">{{ \App\Models\Document::humanDuration($ageSecs) }}</td>
                            <td style="text-align:{{ $a['last_action'] }}">{{ optional($doc->lastActionAt())->format('M j, g:i A') }}</td>
                            <td style="text-align:{{ $a['idle'] }}">{{ $doc->elapsedSinceLastAction() }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            @if($loop->last)
                <div class="summary">
                    <b>{{ $totalCount }}</b> document{{ $totalCount === 1 ? '' : 's' }} total &middot;
                    <b>{{ $openCount }}</b> still open &middot;
                    Avg. age: <b>{{ \App\Models\Document::humanDuration($avgAge) }}</b> &middot;
                    Avg. idle time (working hours, open docs): <b>{{ $avgIdle !== null ? \App\Models\Document::humanDuration($avgIdle) : '—' }}</b>
                </div>
                <div class="note">Idle Time counts only official working hours (8:00 AM–5:00 PM, excluding the 12–1 PM lunch break, Mon–Fri). An action taken after hours shows little or no idle time until the next working day begins — this is expected, not an error.</div>
            @endif
        </div>
    @empty
        <div class="head">
            @if($org)<div class="org">{{ $org }}</div>@endif
            @if(!empty($officeName))<div class="office">{{ $officeName }}</div>@endif
            <div class="title">{{ $reportTitle }}</div>
            <div class="sub">{{ $documentType ?: 'All document types' }} &middot; {{ $period }}{{ $hosp }}</div>
            <div class="gen">Generated by {{ $generatedBy }} &middot; {{ $generatedAt->format('M d, Y g:i A') }}</div>
        </div>
        <p style="text-align:center; color:#777; padding:16px;">No documents found for these filters.</p>
    @endforelse

    @if(!empty($showPageNumber))
    <script type="text/php">
        if (isset($pdf)) {
            $font = $fontMetrics->getFont("DejaVu Sans", "normal");
            $size = 7.5;
            $color = array(0.45, 0.45, 0.45);
            $w = $pdf->get_width();
            $h = $pdf->get_height();
            $pdf->page_text($w - 95, $h - 22, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, $size, $color);
            $pdf->page_text(20, $h - 22, "{{ addslashes($appName) }} · Generated {{ addslashes($generatedAt->format('M d, Y g:i A')) }}", $font, $size, $color);
        }
    </script>
    @endif
</body>
</html>
